LOAD DATA INFILE '../Data/Library.csv'
INTO TABLE Library
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'

LOAD DATA INFILE '../Data/Librarian.csv'
INTO TABLE Librarian
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'

LOAD DATA INFILE '../Data/Checkout.csv'
INTO TABLE Checkout
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'

LOAD DATA INFILE '../Data/Books.csv'
INTO TABLE Books
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'

LOAD DATA INFILE '../Data/User.csv'
INTO TABLE User
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
